spring:
  application:
    name: app

  datasource:
    # env vars set by docker-compose; fallback values used for local development
    url: "${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/reddit}"
    username: "${SPRING_DATASOURCE_USERNAME:postgres}"
    password: "${SPRING_DATASOURCE_PASSWORD:1234}"
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    defer-datasource-initialization: true

  sql:
    init:
      mode: "always"

image-server:
  url: "http://ec2-18-193-138-107.eu-central-1.compute.amazonaws.com:8123"